concurrent = 4

[[runners]]
  name = "Kubernetes Runner"
  url = "http://124.70.29.83/"
  token = "myyiGqMLqC5h_SL_JsXi"
  executor = "kubernetes"
  [runners.kubernetes]
    host = "https://10.88.156.157:5443"
    cert_file = "/etc/ssl/kubernetes/client.crt"
    key_file = "/etc/ssl/kubernetes/client.key"
    ca_file = "/etc/ssl/kubernetes/ca.crt"
    namespace = "gitlab-runner"
    namespace_overwrite_allowed = "ci-.*"
    bearer_token_overwrite_allowed = true
    privileged = true
    cpu_limit = "1"
    memory_limit = "1Gi"
    service_cpu_limit = "1"
    service_memory_limit = "1Gi"
    helper_cpu_limit = "500m"
    helper_memory_limit = "100Mi"
    poll_interval = 5
    poll_timeout = 3600
    [runners.kubernetes.node_selector]
      gitlab = "true"
    [runners.kubernetes.node_tolerations]
      "node-role.kubernetes.io/master" = "NoSchedule"
      "custom.toleration=value" = "NoSchedule"
      "empty.value=" = "PreferNoSchedule"
      "onlyKey" = ""